[package]
name = "descent_unet_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
descent = {git="https://github.com/apexys/descent"}
rand = "0.8"
bytemuck = "1.7"
